emulsify-ds/emulsify-drupal

.storybook/config.js
.storybook/webpack.config.js
components/02-molecules/cta/cta.twig
package.json

Attempt to get [namespacing](https://github.com/twigjs/twig.js/wiki#namespaces) working in the Storybook implementation of Twig.js. 
To work on this PR, install this repo as normal (clone and `yarn`) and then run `yarn develop`
Had to use [this forked twig-loader repo](https://github.com/AmazeeLabs/twig-loader), but it is now working. I'm not crazy about this reality, and have pinged someone at Amazee Labs about it in DrupalTwig Slack. But it is working, so...
To test, just try and edit or add new components that use either the `atoms` or `molecules` namespace.

Twig namespacing

---

emulsify.php

**What & Why:**
When running the PHP script, you can set the path to "custom" (default), "contrib" or "none". There is a use-case for creating an Emulsify project outside of a Drupal install (installing as a standalone prototyping tool). Currently the "none" argument still searches for a Drupal path, and this PR changes it to not do that and instead install it in the parent directory of where it is run. This means that when you clone Emulsify, you can go into that original directory, run `php emulsify.php "New Theme" --machine-name new_theme --path none` and it will generate `new_theme` right alongside your original Emulsify instance. 
**How:**
_This script change is meant to only catch the "none" argument, but I want to make sure it doesn't impact the others._
**To Test:**

PHP script none argument

---

components/02-molecules/tabs/tabs.twig
components/03-organisms/grid/_grid-item.scss
composer.json
emulsify.info.yml
emulsify.theme
package.json
styleguide/0__Getting started/0__Welcome.mdx
styleguide/1__Documentation/1__Storybook.md

Fixes https://github.com/emulsify-ds/emulsify-drupal/issues/54 and switches to `component library` language

Remove Pattern Lab references and also change to component library lingo

---

webpack/loaders.js

**What:**
Updates the webpack loader to support png, jpg, and gif.
**Why:**
To stop errors :)
_Note: I followed the instructions from [here](https://webpack.js.org/guides/asset-management/#loading-images)_

Added support for png, jpg, and gif to the webpack ImageLoader.

---

templates/content/node.html.twig

**What:**
_Fixes Drupal node template teaser heading path_
**Why:**
_Path is broken_
**How:**
_code change_
**To Test:**

GH-69: Fix node teaser heading path

---

package.json

**What:**
_Changes to CI option for start-storybook_
**Why:**
_1. It fixes [this](https://github.com/emulsify-ds/emulsify-drupal/issues/70). 2. I prefer it to not open browser_ ¯\_(ツ)_/¯
**To Test:**

Run Storybook with CI option

---

components/03-organisms/site/site-footer/site-footer.twig

**What:**
_Fixes `<dov>` typo_ See https://github.com/emulsify-ds/emulsify-drupal/issues/87

GH-87: Fix div element

---

package.json

**What:**
I noticed while getting a new project set up that the `storybook` script in `package.json` had an extraneous space before `./images` in its list of static files to serve. This meant that when I tried to use an image housed within my `./images` directory as my theme's logo, or as part of a component, it failed to load. Removing this space resulted in the additional directory's static files being included.

Fixed Storybook script to include images directory

---

components/02-molecules/menus/_menu-item.twig
components/02-molecules/menus/_menu.twig
components/02-molecules/menus/main-menu/_02-main-menu-link.scss

**What:**
_Resorts to using Drupal's `link` function as it is still required to gather all Drupal menu link attributes, but has to use a component fallback for Storybook._
**Why:**
_Drupal links should get more attributes by default (see pics below), and other modules like Menu Attributes interact with those attributes._
**To Test:**
**Before in Drupal:**
**After in Drupal:**

GH-46: Fix menu links to show attributes using link

---

babel.config.js

**What:**
Bumped the corejs major version config for `@babel/preset-env` so that it matches what is specified in `devDependencies` (which was recently updated).
**Why:**
Without this change, babel does not have the correct configuration. I merged some updates from `develop` into my working branch, where I have jest and babel-jest using the babel config, and jest was unable to run due to this major version mismatch. Anything else using this babel config is likely to experience similar issues.
**How:**
Incremented `@babel/preset-env`'s expected major corejs version so that it matches what is installed.
**To Test:**

fix: bump corejs major version in preset-env config so it matches the installed version

---

components/01-atoms/forms/_fieldset.twig

**What:**
Adds `js-form-item` and `js-form-wrapper` (plus their non-JS equivalents) to the array of classes on the `fieldset` element. Also switched to a Twig `{% set %}` tag that includes the original `form-fieldset` class.
**Why:**
Two client sites using Emulsify as a base theme had Webforms with conditionally-visible fieldsets. Without these classes, those fieldsets are always hidden. Discussed via https://www.drupal.org/project/webform/issues/3158073

Add js-form-item/js-form-wrapper classes to fieldset

---

.github/PULL_REQUEST_TEMPLATE.md
.prettierignore
.storybook/_drupal.js
.storybook/config.js
CODE_OF_CONDUCT.md
README.md
components/00-base/01-colors/_00-colors-vars.scss
components/00-base/02-motion/_motion.scss
components/01-atoms/buttons/twig/button.yml
emulsify.info.yml
emulsify.libraries.yml
husky.config.js
lint-staged.config.js
package.json

**What:**
This introduces a few things:
- husky: which allows for npm scripts to be run on commit/push/etc via githooks.
- lint-staged: allows for only staged files to be linted/formatted on commit hooks. This is important, because formatting the entire codebase every time you commit will take way too long, and it will drive you up the wall.
- prettier adjustments: I configured prettier correctly so that it will format js, md, scss, and yml files. I also added a `format` script that runs prettier against eligible files.
**NOTE**
eslint currently is not paying attention to the staged changes, it lints everything. This is necessary for the time being, because eslint needs some adjustment. It shouldn't be linting _only_ the `.components` directory, but rather the entire codebase. I'll see if …

build: add husky and lint-staged, and configure prettier

---

composer.json
jest.config.js

- Adds support for D9 ready version of [Components](https://www.drupal.org/project/components) module
- Changes Jest testing config to ignore `/vendor` (Composer) directory

Fix: Drupal Components module Drupal 9 requirement, jest ignore vendor directory

---

emulsify.php

**What:**
Added the `postcss.config.js` file to the list of things to copy when running `php emulsify.php my_theme`
**Why:**
Builds on the fixes in #115 to allow IE11 compatibility, as raised in #148 
**How:**
Added the `postcss.config.js` file to `_emulsify_get_files_to_copy`
**To Test:**

Fixes #148: Add postcss.config.js to list  of files to copy 

---

.storybook/preview.js
components/04-templates/layouts.stories.js
components/05-pages/content-types/content-types.stories.js
components/05-pages/landing-pages/landing-pages.stories.js

**What:**
Removes these annoying inline styles that prevent full-browser-width components from actually reaching the browser edges (I think this is new to Storybook 6)
**Why:**
It was really annoying
**How:**
There's a config settings in Storybook ([Docs](https://storybook.js.org/docs/react/configure/story-layout))
**To Test:**

Update storybook config to remove unwanted padding.

---

components/00-base/01-colors/colors.twig

Addresses https://github.com/emulsify-ds/emulsify-drupal/issues/109
**To Test:**

Feat/109: Remove 'Theme' from hardcoded into the palette heading

---

emulsify.php

**What:**
_Addresses https://github.com/emulsify-ds/emulsify-drupal/issues/107 by copying over the README but leaving it as-is._
**To Test:**

Feat/107: Remove README during custom theme creation

---

jest.config.js

**What:**
Adjusts Jest configuration so that it can ignore .test.js files that exist within the build destination folder.
**Why:**
Running `yarn test` while .test.js files exist within the build destination folder currently results in Jest picking up those files, and then failing the tests within them.
**How:**
Added the build destination directory to the list of folders for Jest to ignore.
**To Test:**

fix: jest should ignore the .out directory when looking for tests

---

components/01-atoms/images/icons/icons.md

**What:**
Adjusted documentation to prevent `static_tests` from failing due to "Line exceeds 80 characters" errors
**Why:**
When incorporating CI practices after creating a new Emulsify theme, the `icons.md` file fails `static_tests` (a default test at least from Pantheon Build Tools) because some line lengths are more than 80 characters. I've had to make this minor tweak on each Emulsify-based project I've started.

Adjust line length to prevent CI test failure

---

composer.json

**What:**
Updates components from `2.0.0-beta3` to `^2.0`
**Why:**
- Drupal 9 requires 2.x of components
- So that we are updating to the latest stable release when available.
**How:**
Updated `composer.json` dependency.
**To Test:**

feat(components): Updates components from pinned version to semantic release.

---

emulsify.php

**What:**
_After running emulsify.php with the (possibly undocumented) --slim option I found that I would encounter errors on the first run of storybook due to missing components._
**Why:**
_At Bounteous we're re-evaluating our front end starter kit, so I'm taking another hands on spin around the Drupal component landscape (I have a habit of doing that anyway.) The audience for this is probably pretty small, but I personally see value in being able to spin up an Emulsify project with all of the tooling structure, but no existing opinions or styles or components._
**How:**
Was encountering this error when running storybook:
`ERROR in ./components/00-base/01-colors/colors.twig
Module not found: Error: Can't resolve '/Users/brianperry/repos/fe-starter-sandbox/web/themes/custom/emulsify_test/c …

Remove colors from --slim option to prevent errors during initial Storybook run

---

components/01-atoms/images/icons/_icons.scss

Just a minor quality-of-life adjustment I tend to make on new projects, so I thought I'd suggest it: for lengthier lists of icons, this wraps the list to multiple lines so that you can see more icons on the page, instead of them extending on a single line to the point where you have to scroll horizontally to see more of the list.

Add flex-wrap to Storybook styles for icons

---

emulsify.info.yml

I noticed on a new project today that I was getting the following watchdog log entry:
_Components 8.x-1.x API is deprecated in components:8.x-2.0 and is removed from components:3.0.0. Update the trailhead_theme.info.yml file to replace the component-libraries.[namespace].paths data with components.namespaces.[namespace]. See https://www.drupal.org/node/3082817_
It looks like the structure of the Twig namespaces has changed slightly. This PR updates the `.info.yml` file to match the structure [documented on Drupal.org](https://www.drupal.org/docs/contributed-modules/components/registering-twig-namespaces). I changed this on my new project and it's working just fine, but haven't done much component work on it yet, so additional review is appreciated!

Update components Twig namespaces to reflect API changes

---

.storybook/webpack.config.js

fix 211
fixes  `ERROR in No files matching '/home/XXXXXX/Downloads/emulsify-drupal/.storybook/storybook-init-framework-entry.js' were found` when running `yarn develop
**To Test:**
more info in the issue: https://github.com/emulsify-ds/emulsify-drupal/issues/211#

fix: update eslint-webpack-plugin configuration to only scope components

---

components/02-molecules/pager/pager-first-last.yml
components/02-molecules/pager/pager.stories.js
components/02-molecules/pager/pager.twig

I've noticed that, especially when building Views in Drupal that have full pagination, those pagers' First and Last items aren't rendered, only the Previous and Next items and the page numbers surrounding the current page. This adds those to the Pager Twig template, along with a variant in Storybook. (I used the full words and guillemets, but feel free to adjust how these get rendered if something else makes more sense alongside the arrows replacing the Previous and Next labels.)

Add first and last items to Pager component

---

package.json
patches/twig+1.15.4.patch

**What:**
fix: file.includes errors
**Why:**
When you have components with the pattern of:
include > include > embed
you get an error about file.includes is not a function, this patch fixes this, it is from the upstream repo and is uncommitted.
**To Test:**

fix: file.includes errors

---

package.json

**What:**
The command "storybook-build" is not working because it is referencing itself.
**Why:**
Bug
**How:**
The correct storybook command is "build-storybook so the line should read:
`"storybook-build": "npm run build && build-storybook -s ./dist,./images -o .out",`
Fixes: https://github.com/emulsify-ds/emulsify-drupal/issues/240

Fixed incorrect npm script command

---

.eslintignore
.prettierignore
.stylelintignore

ESLint, Prettier, and Stylelint ignore the node_modules directory by
default.

Remove node_modules directory from ignore files

---

webpack/plugins.js
webpack/webpack.common.js

re #246
**What:**
Modify webpack config to compile multiple scss files into multiple css files while keeping the current, default style.css file in place.
**Why:**
This will allow developers more flexibility, ability to choose between consuming the single style.css or splitting it to multiple libraries.It also set a foundation for developing storybook components in isolation. 
**How:**
In webpack/webpack.common.js  file 
I modified getEntries function to process multiple scss files entries the same way it already does for JS files.
So it will output multiple css files into new dist/css folder  the same way it currently does with JS in dist/js folder
In webpack/plugins.js  file 
1.  I changed MiniCssExtractPlugin filename parameter to be dynamic, [name].css, instead of being hardcoded …

Configure webpack to compile multiple css files

---

.storybook/setupTwig.js
.storybook/setupTwig.test.js
package-lock.json
package.json
scripts/a11y.test.js

**What:**
This pull request makes several small updates to get tests to work appropriately.
**Why:**
Tests should pass. :)
**How:**
* setupTwig.test.js updated namespaces to the current list of namespaces.
* a11y.test.js had regenerator-runtime/runtime added to get the test to run correctly. (This resolution is from https://dev.to/hulyakarakaya/how-to-fix-regeneratorruntime-is-not-defined-doj.)
**To Test:**
This resolves #255.

Fix testing scripts

---

.gitignore

**What:**
Ignore .idea and .vscode files from IDEs.
**Why:**
Prevents accidental IDE config from being pushed.

Ignore config files for VSCode and JetBrains IDEs.

---

webpack/css/style.js
webpack/webpack.common.js

**What:**
Update style.scss compiling to match docs for "In webpack.common.js replace" here https://docs.emulsify.info/supporting-projects/webpack-and-build
**Why:**
Compiling style.scss is broken after PR #247.

fix: Compiling style.scss after PR #247.

---

.gitignore
package.json

**What:**
This pull request migrates yarn references to npm and blocks committing a yarn.lock file to the repo.
**Why:**
Using yarn and npm interchangeably is confusing, so we are standardizing on npm.
**How:**
Script references in package.json were converted from `yarn ...` to `npm run ...`.
**To Test:**
Closes #250

Standardize on npm

---

composer.json
emulsify.info.yml

**What:**
Adds module dependencies to info.yml file and removes references to those modules in composer.json file to reduce confusion. Addresses #75 
**Why:**
Prevents installation of the created Emulsify-based theme until the correct modules (components and emulsify_twig) are installed. This helps eliminate confusion if the theme doesn't work properly without these modules installed.
**How:**
Added the two required modules to the dependencies section of the emulsify.info.yml file and removed the two modules from the composer.json file.
**To Test:**

Issue 75 drupal module dependencies

---

webpack/plugins.js

**What:**
Drupal could not find style.css because it was being removed.
**Why:**
This PR fixes it so style.css does not get removed.
**How:**
Modified the "cleanAfterEveryBuildPatterns" array to remove the entry `'css/style.*'`.
**To Test:**

fix: Missing style.css after PR #247.

---

emulsify.info.yml

**What:**
Enable starter to be D10 compatible.
**Why:**
Without this change, a manual change of the info.yml is necessary for D10.
**How:**
After using the change in this branch and the change here ( https://git.drupalcode.org/project/emulsify_twig/-/merge_requests/4 ) to emulsify_twig module , then Emulsify works with D10.
See this issues and explanation for dropping D8 here ( https://www.drupal.org/project/emulsify_twig/issues/3301353 )

Deprecating D8 and enabling D10

---

emulsify.info.yml

**What:**
Removes `core` key in emulsify.info.yml so emulsify CLI install can complete
**Why:**
CLI install is currently broken due to the core key being present

fix: remove core key as it's deprecated

---

composer.json
emulsify.info.yml

**What:**
Updates Emulsify Twig dependency to ^4.0 which is now the latest version of Emulsify Twig.
**Why:**
Emulsify Twig 4.0 is Drupal 10 ready and also works on Drupal 9. Drupal 8 support was dropped.
**How:**
Updated emulsify.info.yml with dependency change.
**To Test:**

Update Emulsify Twig dependency

---

.cli/init.js
package-lock.json
package.json

The safeLoad and safeDump functions are removed in js-yaml v4 - they are now safe by default. This corrects an error thrown when initializing a new drupal theme. It also adds js-yaml as an explicit dependency.
**What:**
The `js-yaml` `safeLoad` and `safeDump` functions are replaced with `load` and `dump` respectively. `js-yaml` is added as an explicit dependency.
**Why:**
Currently, the `emulsify-drupal` starter errors out due to the use of functions removed from `js-yaml@4`. This means the starter is non-functional. This change makes it functional again.
**How:**
Simply put, this just catches the starter up to its dependencies changes and makes an implicit dependency explicit.
**To Test:**
```
npx @emulsify/cli init "My Project" -s https://github.com/andycarlberg/emulsify-drupal/ -c …
```

Update init.js script to match js-yaml deprecations.

---

emulsify.php

**What:**
Coding standards fixes over emulsify.php file
**Why:**
Automatic php lint tools (phpcs) throws multiple errors while reading this file
**How:**
Replaced old code or bad practices with new good practices
**To Test:**
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/85ztnbn1z) by [Unito](https://www.unito.io)

Multiple php Coding standards fixes for the emulsify.php file

---

.stylelintrc.json

Since there was an update to Node 20, the Stylelin version were upgraded too, this is not happening on Compound, this PR fixes the new warnings the are being displayed because of those upgrades.
**This PR must be tested together with this [PR](https://github.com/emulsify-ds/compound/pull/104)**
Create Drupal Project:
`composer create-project drupal/recommended-project [PROJECT_NAME] --no-interaction `
Move into the project directory
`cd [PROJECT_NAME]`
Install Emulsify client globally
`npm install -g @emulsify/cli`
Initialize your theme with emulsify
`emulsify init --checkout=fix-stylelint-issues "[THEME NAME]"`
Install the version of Drupal componentst works with Drupal 10
`composer require 'drupal/components:^3.0@beta'  `
Install the version of emulsify_twig that work with Drupal 10 …

Fix(stylelint issues): Adjusting stylelint rule settings.

---

emulsify.info.yml

**What:**
- Updates Emulsify Twig supported version to 5.0
**Why:**
- 4.x was deprecated due to dropping support for Drupal 9.x
**To Test:**

feat: add version 5.0 as supported emulsify_twig

---

composer.json

- Updates the Emulsify Tools dependency to the 1.x stable release.
- (optional) Document any intentionally unfinished parts or known issues within this PR

fix: update Emulsify Tools to 1.x stable release

---

whisk/config/emulsify-core/storybook/main.js

- Set up a default main.js that is consumed by Emulsify Core and gives an example of storybook config. 
- None
```
managerHead: (head) => `
${head}
<style>
:root {
--colors-emulsify-blue-100: #e6f5fc;
--colors-emulsify-blue-200: #CCECFA;
--colors-emulsify-blue-300: #99D9F4;
--colors-emulsify-blue-400: #66c5ef;
--colors-emulsify-blue-500: #33b2e9;
--colors-emulsify-blue-600: #009fe4;
--colors-emulsify-blue-700: #007FB6;
--colors-emulsify-blue-800: #005f89;
--colors-emulsify-blue-900: #00405b;
--colors-emulsify-blue-1000: #00202e;
--colors-purple: #8B1E7E;
}
</style>
`,
```

feat: add default main.js to config that passes an empty object

---

whisk/config/emulsify-core/storybook/preview.js
whisk/package.json

- Upgrade Emulsify Core to 2.0 for more flexible CSS/JS compiling, support for SDC components, and Storybook8

feat: remove default components folder and upgrade Emulsify Core to 2.0

---

emulsify.info.yml
whisk/package.json
whisk/whisk.info.emulsify.yml

- Updates emulsify/core to version `2.2.3`
- Updates whisk component namespaces to include a non-atomic component structure
- https://fourkitchens.clickup.com/t/36718269/EMULSIF-362

EMULSIF-362: update package to use emulsify 2.2.3. Update namespaces

---

whisk/package.json

- Lets use the latest version of Emulsify Core

fix: emulsify-core version bump
